-- MySQL Script generated by MySQL Workbench
-- Thu Mar  9 14:19:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `LibraryDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` INT NOT NULL,
  `password` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `surname_UNIQUE` (`surname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `volume` INT NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `editor` VARCHAR(255) NOT NULL,
  `price` DECIMAL(0) NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Books_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `LibraryDB`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryDB`.`Borrowed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Borrowed` (
  `Books_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `state` ENUM("emprunté", "libre") NOT NULL,
  PRIMARY KEY (`Books_id`, `Users_id`),
  INDEX `fk_Books_has_Users_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Books_has_Users_Books1_idx` (`Books_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_has_Users_Books1`
    FOREIGN KEY (`Books_id`)
    REFERENCES `LibraryDB`.`Books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_has_Users_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `LibraryDB`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
